//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderPosition = new HashSet<OrderPosition>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int NumberOfVisitiors { get; set; }
        public int TableId { get; set; }
        public int EmployeeId { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime DateOfAccept { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Table Table { get; set; }
        public virtual ICollection<OrderPosition> OrderPosition { get; set; }
    }
}
