//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPosition
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int PositionId { get; set; }
        public bool IsReady { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Position Position { get; set; }
    }
}
